{{- if and .Values.pdb.enabled (gt (int .Values.replicas) 1) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "silo.fullname" . }}
  labels:
    {{- include "silo.labels" . | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  selector:
    matchLabels:
      {{- include "silo.selectorLabels" . | nindent 6 }}
{{- end }}
