{{- if and .Values.metrics.enabled .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "silo.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.serviceMonitor.namespace }}
  labels:
    {{- include "silo.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "silo.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      monitoring: "true"
  endpoints:
    - port: {{ ternary "https" "http" .Values.tls.enabled }}
      scheme: {{ ternary "https" "http" .Values.tls.enabled }}
      path: {{ .Values.metrics.serviceMonitor.path | quote }}
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout }}
{{- end }}
